// File generated by FlutterFire CLI / Firebase Configuration Architecture
// Project: ma Store (ma-store-949c7)
// Project Number: 611361603523
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for macOS.');
      case TargetPlatform.windows:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for Windows.');
      case TargetPlatform.linux:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for Linux.');
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_placeholder_for_client_sdk_init',
    appId: '1:611361603523:web:rama_store_app',
    messagingSenderId: '611361603523',
    projectId: 'ma-store-949c7',
    authDomain: 'ma-store-949c7.firebaseapp.com',
    storageBucket: 'ma-store-949c7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_placeholder_for_client_sdk_init',
    appId: '1:611361603523:android:com.ramastore.rama_store_app',
    messagingSenderId: '611361603523',
    projectId: 'ma-store-949c7',
    storageBucket: 'ma-store-949c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_placeholder_for_client_sdk_init',
    appId: '1:611361603523:ios:com.ramastore.ramaStoreApp',
    messagingSenderId: '611361603523',
    projectId: 'ma-store-949c7',
    storageBucket: 'ma-store-949c7.firebasestorage.app',
    iosBundleId: 'com.ramastore.ramaStoreApp',
  );
}
